initial commit
fortinet-fortisoar/connector-itglue pull request #1
Opened 2021-08-17 13:05 UTC by securecyberdefense

2022-06-16 05:05 UTC, cs-shravan-konthalapally requested changes
change the folder name to itglue.

2022-06-16 05:08 UTC, cs-shravan-konthalapally requested changes
Add the logger and exception handling/change the folder structure

2022-06-16 05:08 UTC, cs-shravan-konthalapally commented on ITGlue/health_check.py
> +    # TODO: implement health check for the connector here
Verify the configuration using the API key from configuration

2022-06-16 05:08 UTC, cs-shravan-konthalapally commented on ITGlue/itglueapi.py
> +        response = request(method='get', url=url, params=params, headers=headers)
Add logging and exception handling

2022-06-28 06:51 UTC, merged

2022-06-28 06:52 UTC, cs-prerna-joshi commented
Integration Team will take care of the changes required.